### ISSUE TITLE
[BUG] IEDs do not detonate when destroyed

### ISSUE THREAD

**Issue by Slatery** [Walthzer/RID#26]
**Describe the bug**
IEDs placed from the module do not detonate when destroyed. 
i.e. a sapper places a demolition charge to detonate the IED, the IED will be killed but the object remain and no secondary explosive.

**To Reproduce**
1. Place IED using module
2. "kill" the IED (shoot it, use an explosive next to it, set health to 0 in Zeus)

**Expected behavior**
IED is expected to detonate, or be removed/destroyed. If not all the time then some of the time

**Screenshots**
![image](https://user-images.githubusercontent.com/30992793/111865844-4dabec80-89b9-11eb-8787-de8875e6ec66.png)
![image](https://user-images.githubusercontent.com/30992793/111865898-a9767580-89b9-11eb-856b-9b98bf94f530.png)
![image](https://user-images.githubusercontent.com/30992793/111865900-b2674700-89b9-11eb-8b4e-721724c8a36c.png)

**Additional context**
Tested with Workshop versions of ACE, CBA, ZEN and RID

**Comment by Walthzer** [comment]
Check #20

**Comment by Slatery** [comment]
closing for duplicate
